package com.example.anyam

object DataItem {
    private val namaItem = arrayOf(
        "Bantal Duduk Model 1 lonvkldfsvo sovijs ifjhj u g iu jghjbjk yhj",
        "Bantal Duduk Model 2",
        "Keranjang Model 1",
        "Keranjang Model 2",
        "Keranjang Model 3",
        "Keranjang Model 4",
        "Tas Model 1",
        "Tas Model 2",
        "Tas Model 3",
        "Tas Model 4",
        "Tas Model 5",
        "Tas Model 5",
        "Tas Model 7",
        "Tas Model 8",
        "Tas Model 9",
        "Bantal Duduk Model 1",
        "Bantal Duduk Model 2",
        "Keranjang Model 1",
        "Keranjang Model 2",
        "Keranjang Model 3",
        "Keranjang Model 4",
        "Tas Model 1",
        "Tas Model 2",
        "Tas Model 3",
        "Tas Model 4",
        "Tas Model 5",
        "Tas Model 5",
        "Tas Model 7",
        "Tas Model 8",
        "Tas Model 9"
    )

    private val hargaItem = doubleArrayOf(
        80000.0,
        65000.0,
        85000.0,
        50000.0,
        120000.0,
        80000.0,
        65000.0,
        85000.0,
        50000.0,
        120000.0,
        80000.0,
        65000.0,
        85000.0,
        50000.0,
        120000.0,
        80000.0,
        65000.0,
        85000.0,
        50000.0,
        120000.0,
        80000.0,
        65000.0,
        85000.0,
        50000.0,
        120000.0,
        80000.0,
        65000.0,
        85000.0,
        50000.0,
        120000.0
    )

    private val deskripsiItem = arrayOf(
        "Ini adalah bantal duduk model 1 dengan bahan bahan pilihan serta di buat dengan teknik khusus oleh penganyam profesional.\nBahan utama dari bantal duduk model 1 ini adalah eceng gondok yang di olah menggunakan teknik khusus sehingga menghasilkan produk yang berkialitas.\nTahan terhadap rayap dan awet karena telah dilapisi oleh cairan khusus yang tentunya aman bagi kulit",
        "Ini adalah bantal duduk model 2 dengan bahan bahan pilihan serta di buat dengan teknik khusus oleh penganyam profesional.\nBahan utama dari bantal duduk model 2 ini adalah eceng gondok yang di olah menggunakan teknik khusus sehingga menghasilkan produk yang berkialitas.\nTahan terhadap rayap dan awet karena telah dilapisi oleh cairan khusus yang tentunya aman bagi kulit Ini adalah bantal duduk model 2 dengan bahan bahan pilihan serta di buat dengan teknik khusus oleh penganyam profesional adalah bantal duduk model 2 dengan bahan bahan pilihan serta di buat dengan teknik khusus oleh penganyam profesional adalah bantal duduk model 2 dengan bahan bahan pilihan serta di buat dengan teknik khusus oleh penganyam profesional adalah bantal duduk model 2 dengan bahan bahan pilihan serta di buat dengan teknik khusus oleh penganyam profesional adalah bantal duduk model 2 dengan bahan bahan pilihan serta di buat dengan teknik khusus oleh penganyam profesional.",
        "Ini adalah kernajang model 1 dengan bahan bahan pilihan serta di buat dengan teknik khusus oleh penganyam profesional.\nBahan utama dari kernajang model 1 ini adalah eceng gondok yang di olah menggunakan teknik khusus sehingga menghasilkan produk yang berkialitas.\nTahan terhadap rayap dan awet karena telah dilapisi oleh cairan khusus yang tentunya aman bagi kulit",
        "Ini adalah kernajang model 2 dengan bahan bahan pilihan serta di buat dengan teknik khusus oleh penganyam profesional.\nBahan utama dari kernajang model 2 ini adalah eceng gondok yang di olah menggunakan teknik khusus sehingga menghasilkan produk yang berkialitas.\nTahan terhadap rayap dan awet karena telah dilapisi oleh cairan khusus yang tentunya aman bagi kulit",
        "Ini adalah kernajang model 3 dengan bahan bahan pilihan serta di buat dengan teknik khusus oleh penganyam profesional.\nBahan utama dari kernajang model 3 ini adalah eceng gondok yang di olah menggunakan teknik khusus sehingga menghasilkan produk yang berkialitas.\nTahan terhadap rayap dan awet karena telah dilapisi oleh cairan khusus yang tentunya aman bagi kulit",
        "Ini adalah kernajang model 4 dengan bahan bahan pilihan serta di buat dengan teknik khusus oleh penganyam profesional.\nBahan utama dari kernajang model 4 ini adalah eceng gondok yang di olah menggunakan teknik khusus sehingga menghasilkan produk yang berkialitas.\nTahan terhadap rayap dan awet karena telah dilapisi oleh cairan khusus yang tentunya aman bagi kulit",
        "Ini adalah tas model 1 dengan bahan bahan pilihan serta di buat dengan teknik khusus oleh penganyam profesional.\nBahan utama dari tas model 1 ini adalah eceng gondok yang di olah menggunakan teknik khusus sehingga menghasilkan produk yang berkialitas.\nTahan terhadap rayap dan awet karena telah dilapisi oleh cairan khusus yang tentunya aman bagi kulit",
        "Ini adalah tas model 2 dengan bahan bahan pilihan serta di buat dengan teknik khusus oleh penganyam profesional.\nBahan utama dari tas model 2 ini adalah eceng gondok yang di olah menggunakan teknik khusus sehingga menghasilkan produk yang berkialitas.\nTahan terhadap rayap dan awet karena telah dilapisi oleh cairan khusus yang tentunya aman bagi kulit",
        "Ini adalah tas model 3 dengan bahan bahan pilihan serta di buat dengan teknik khusus oleh penganyam profesional.\nBahan utama dari tas model 3 ini adalah eceng gondok yang di olah menggunakan teknik khusus sehingga menghasilkan produk yang berkialitas.\nTahan terhadap rayap dan awet karena telah dilapisi oleh cairan khusus yang tentunya aman bagi kulit",
        "Ini adalah tas model 4 dengan bahan bahan pilihan serta di buat dengan teknik khusus oleh penganyam profesional.\nBahan utama dari tas model 4 ini adalah eceng gondok yang di olah menggunakan teknik khusus sehingga menghasilkan produk yang berkialitas.\nTahan terhadap rayap dan awet karena telah dilapisi oleh cairan khusus yang tentunya aman bagi kulit",
        "Ini adalah tas model 5 dengan bahan bahan pilihan serta di buat dengan teknik khusus oleh penganyam profesional.\nBahan utama dari tas model 5 ini adalah eceng gondok yang di olah menggunakan teknik khusus sehingga menghasilkan produk yang berkialitas.\nTahan terhadap rayap dan awet karena telah dilapisi oleh cairan khusus yang tentunya aman bagi kulit",
        "Ini adalah tas model 6 dengan bahan bahan pilihan serta di buat dengan teknik khusus oleh penganyam profesional.\nBahan utama dari tas model 6 ini adalah eceng gondok yang di olah menggunakan teknik khusus sehingga menghasilkan produk yang berkialitas.\nTahan terhadap rayap dan awet karena telah dilapisi oleh cairan khusus yang tentunya aman bagi kulit",
        "Ini adalah tas model 7 dengan bahan bahan pilihan serta di buat dengan teknik khusus oleh penganyam profesional.\nBahan utama dari tas model 7 ini adalah eceng gondok yang di olah menggunakan teknik khusus sehingga menghasilkan produk yang berkialitas.\nTahan terhadap rayap dan awet karena telah dilapisi oleh cairan khusus yang tentunya aman bagi kulit",
        "Ini adalah tas model 8 dengan bahan bahan pilihan serta di buat dengan teknik khusus oleh penganyam profesional.\nBahan utama dari tas model 8 ini adalah eceng gondok yang di olah menggunakan teknik khusus sehingga menghasilkan produk yang berkialitas.\nTahan terhadap rayap dan awet karena telah dilapisi oleh cairan khusus yang tentunya aman bagi kulit",
        "Ini adalah tas model 9 dengan bahan bahan pilihan serta di buat dengan teknik khusus oleh penganyam profesional.\nBahan utama dari tas model 9 ini adalah eceng gondok yang di olah menggunakan teknik khusus sehingga menghasilkan produk yang berkialitas.\nTahan terhadap rayap dan awet karena telah dilapisi oleh cairan khusus yang tentunya aman bagi kulit",
        "Ini adalah bantal duduk model 1 dengan bahan bahan pilihan serta di buat dengan teknik khusus oleh penganyam profesional.\nBahan utama dari bantal duduk model 1 ini adalah eceng gondok yang di olah menggunakan teknik khusus sehingga menghasilkan produk yang berkialitas.\nTahan terhadap rayap dan awet karena telah dilapisi oleh cairan khusus yang tentunya aman bagi kulit",
        "Ini adalah bantal duduk model 2 dengan bahan bahan pilihan serta di buat dengan teknik khusus oleh penganyam profesional.\nBahan utama dari bantal duduk model 2 ini adalah eceng gondok yang di olah menggunakan teknik khusus sehingga menghasilkan produk yang berkialitas.\nTahan terhadap rayap dan awet karena telah dilapisi oleh cairan khusus yang tentunya aman bagi kulit Ini adalah bantal duduk model 2 dengan bahan bahan pilihan serta di buat dengan teknik khusus oleh penganyam profesional.",
        "Ini adalah kernajang model 1 dengan bahan bahan pilihan serta di buat dengan teknik khusus oleh penganyam profesional.\nBahan utama dari kernajang model 1 ini adalah eceng gondok yang di olah menggunakan teknik khusus sehingga menghasilkan produk yang berkialitas.\nTahan terhadap rayap dan awet karena telah dilapisi oleh cairan khusus yang tentunya aman bagi kulit",
        "Ini adalah kernajang model 2 dengan bahan bahan pilihan serta di buat dengan teknik khusus oleh penganyam profesional.\nBahan utama dari kernajang model 2 ini adalah eceng gondok yang di olah menggunakan teknik khusus sehingga menghasilkan produk yang berkialitas.\nTahan terhadap rayap dan awet karena telah dilapisi oleh cairan khusus yang tentunya aman bagi kulit",
        "Ini adalah kernajang model 3 dengan bahan bahan pilihan serta di buat dengan teknik khusus oleh penganyam profesional.\nBahan utama dari kernajang model 3 ini adalah eceng gondok yang di olah menggunakan teknik khusus sehingga menghasilkan produk yang berkialitas.\nTahan terhadap rayap dan awet karena telah dilapisi oleh cairan khusus yang tentunya aman bagi kulit",
        "Ini adalah kernajang model 4 dengan bahan bahan pilihan serta di buat dengan teknik khusus oleh penganyam profesional.\nBahan utama dari kernajang model 4 ini adalah eceng gondok yang di olah menggunakan teknik khusus sehingga menghasilkan produk yang berkialitas.\nTahan terhadap rayap dan awet karena telah dilapisi oleh cairan khusus yang tentunya aman bagi kulit",
        "Ini adalah tas model 1 dengan bahan bahan pilihan serta di buat dengan teknik khusus oleh penganyam profesional.\nBahan utama dari tas model 1 ini adalah eceng gondok yang di olah menggunakan teknik khusus sehingga menghasilkan produk yang berkialitas.\nTahan terhadap rayap dan awet karena telah dilapisi oleh cairan khusus yang tentunya aman bagi kulit",
        "Ini adalah tas model 2 dengan bahan bahan pilihan serta di buat dengan teknik khusus oleh penganyam profesional.\nBahan utama dari tas model 2 ini adalah eceng gondok yang di olah menggunakan teknik khusus sehingga menghasilkan produk yang berkialitas.\nTahan terhadap rayap dan awet karena telah dilapisi oleh cairan khusus yang tentunya aman bagi kulit",
        "Ini adalah tas model 3 dengan bahan bahan pilihan serta di buat dengan teknik khusus oleh penganyam profesional.\nBahan utama dari tas model 3 ini adalah eceng gondok yang di olah menggunakan teknik khusus sehingga menghasilkan produk yang berkialitas.\nTahan terhadap rayap dan awet karena telah dilapisi oleh cairan khusus yang tentunya aman bagi kulit",
        "Ini adalah tas model 4 dengan bahan bahan pilihan serta di buat dengan teknik khusus oleh penganyam profesional.\nBahan utama dari tas model 4 ini adalah eceng gondok yang di olah menggunakan teknik khusus sehingga menghasilkan produk yang berkialitas.\nTahan terhadap rayap dan awet karena telah dilapisi oleh cairan khusus yang tentunya aman bagi kulit",
        "Ini adalah tas model 5 dengan bahan bahan pilihan serta di buat dengan teknik khusus oleh penganyam profesional.\nBahan utama dari tas model 5 ini adalah eceng gondok yang di olah menggunakan teknik khusus sehingga menghasilkan produk yang berkialitas.\nTahan terhadap rayap dan awet karena telah dilapisi oleh cairan khusus yang tentunya aman bagi kulit",
        "Ini adalah tas model 6 dengan bahan bahan pilihan serta di buat dengan teknik khusus oleh penganyam profesional.\nBahan utama dari tas model 6 ini adalah eceng gondok yang di olah menggunakan teknik khusus sehingga menghasilkan produk yang berkialitas.\nTahan terhadap rayap dan awet karena telah dilapisi oleh cairan khusus yang tentunya aman bagi kulit",
        "Ini adalah tas model 7 dengan bahan bahan pilihan serta di buat dengan teknik khusus oleh penganyam profesional.\nBahan utama dari tas model 7 ini adalah eceng gondok yang di olah menggunakan teknik khusus sehingga menghasilkan produk yang berkialitas.\nTahan terhadap rayap dan awet karena telah dilapisi oleh cairan khusus yang tentunya aman bagi kulit",
        "Ini adalah tas model 8 dengan bahan bahan pilihan serta di buat dengan teknik khusus oleh penganyam profesional.\nBahan utama dari tas model 8 ini adalah eceng gondok yang di olah menggunakan teknik khusus sehingga menghasilkan produk yang berkialitas.\nTahan terhadap rayap dan awet karena telah dilapisi oleh cairan khusus yang tentunya aman bagi kulit",
        "Ini adalah tas model 9 dengan bahan bahan pilihan serta di buat dengan teknik khusus oleh penganyam profesional.\nBahan utama dari tas model 9 ini adalah eceng gondok yang di olah menggunakan teknik khusus sehingga menghasilkan produk yang berkialitas.\nTahan terhadap rayap dan awet karena telah dilapisi oleh cairan khusus yang tentunya aman bagi kulit"
    )

//    private val gambarItem = intArrayOf(
//        R.drawable.bantal_duduk_model1,
//        R.drawable.bantal_duduk_model2,
//        R.drawable.keranjang_model1,
//        R.drawable.keranjang_model2,
//        R.drawable.keranjang_model3,
//        R.drawable.keranjang_model4,
//        R.drawable.tas_model1,
//        R.drawable.tas_model2,
//        R.drawable.tas_model3,
//        R.drawable.tas_model4,
//        R.drawable.tas_model5,
//        R.drawable.tas_model6,
//        R.drawable.tas_model7,
//        R.drawable.tas_model8,
//        R.drawable.tas_model9,
//        R.drawable.bantal_duduk_model1,
//        R.drawable.bantal_duduk_model2,
//        R.drawable.keranjang_model1,
//        R.drawable.keranjang_model2,
//        R.drawable.keranjang_model3,
//        R.drawable.keranjang_model4,
//        R.drawable.tas_model1,
//        R.drawable.tas_model2,
//        R.drawable.tas_model3,
//        R.drawable.tas_model4,
//        R.drawable.tas_model5,
//        R.drawable.tas_model6,
//        R.drawable.tas_model7,
//        R.drawable.tas_model8,
//        R.drawable.tas_model9
//
//    )

    private val gambarCarousel = arrayOf(
            intArrayOf(R.drawable.bantal_duduk_model1,
                    R.drawable.bantal_duduk_model2,
                    R.drawable.keranjang_model1,
                    R.drawable.keranjang_model2,
                    R.drawable.keranjang_model3,
                    R.drawable.keranjang_model4,
                    R.drawable.tas_model1),
            intArrayOf(R.drawable.bantal_duduk_model2,
                    R.drawable.tas_model5,
                    R.drawable.tas_model6,
                    R.drawable.tas_model7,
                    R.drawable.tas_model8,
                    R.drawable.tas_model9),
            intArrayOf(R.drawable.keranjang_model1,
                    R.drawable.keranjang_model1,
                    R.drawable.keranjang_model2,
                    R.drawable.keranjang_model3,
                    R.drawable.keranjang_model4,
                    R.drawable.tas_model1),
            intArrayOf(R.drawable.keranjang_model2,
                    R.drawable.tas_model1,
                    R.drawable.tas_model2,
                    R.drawable.tas_model3,
                    R.drawable.tas_model4),
            intArrayOf(R.drawable.keranjang_model3,
                    R.drawable.bantal_duduk_model1,
                    R.drawable.bantal_duduk_model2,
                    R.drawable.keranjang_model1,
                    R.drawable.keranjang_model2,
                    R.drawable.keranjang_model3,
                    R.drawable.keranjang_model4,
                    R.drawable.tas_model1),
            intArrayOf(R.drawable.keranjang_model4,
                    R.drawable.tas_model5,
                    R.drawable.tas_model6,
                    R.drawable.tas_model7,
                    R.drawable.tas_model8,
                    R.drawable.tas_model9),
            intArrayOf(R.drawable.tas_model1,
                    R.drawable.bantal_duduk_model2,
                    R.drawable.keranjang_model1,
                    R.drawable.keranjang_model2,
                    R.drawable.keranjang_model3,
                    R.drawable.keranjang_model4,
                    R.drawable.tas_model1),
            intArrayOf(R.drawable.tas_model2,
                    R.drawable.tas_model5,
                    R.drawable.tas_model6,
                    R.drawable.tas_model7,
                    R.drawable.tas_model8,
                    R.drawable.tas_model9),
            intArrayOf(R.drawable.tas_model3,
                    R.drawable.bantal_duduk_model2,
                    R.drawable.keranjang_model1,
                    R.drawable.keranjang_model2,
                    R.drawable.keranjang_model3,
                    R.drawable.keranjang_model4,
                    R.drawable.tas_model1),
            intArrayOf(R.drawable.tas_model4,
                    R.drawable.tas_model1,
                    R.drawable.tas_model2,
                    R.drawable.tas_model3,
                    R.drawable.tas_model4),
            intArrayOf(R.drawable.tas_model5,
                    R.drawable.bantal_duduk_model1,
                    R.drawable.bantal_duduk_model2,
                    R.drawable.keranjang_model1,
                    R.drawable.keranjang_model2,
                    R.drawable.keranjang_model3,
                    R.drawable.keranjang_model4,
                    R.drawable.tas_model1),
            intArrayOf(R.drawable.tas_model6,
                    R.drawable.tas_model6,
                    R.drawable.tas_model7,
                    R.drawable.tas_model8,
                    R.drawable.tas_model9),
            intArrayOf(R.drawable.tas_model7,
                    R.drawable.bantal_duduk_model1,
                    R.drawable.bantal_duduk_model2,
                    R.drawable.keranjang_model1,
                    R.drawable.keranjang_model2,
                    R.drawable.keranjang_model3,
                    R.drawable.keranjang_model4,
                    R.drawable.tas_model1),
            intArrayOf(R.drawable.tas_model8,
                    R.drawable.tas_model6,
                    R.drawable.tas_model7,
                    R.drawable.tas_model8,
                    R.drawable.tas_model9),
            intArrayOf(R.drawable.tas_model9,
                    R.drawable.bantal_duduk_model2,
                    R.drawable.keranjang_model1,
                    R.drawable.keranjang_model2,
                    R.drawable.keranjang_model3,
                    R.drawable.keranjang_model4,
                    R.drawable.tas_model1),
            intArrayOf(R.drawable.bantal_duduk_model1,
                    R.drawable.bantal_duduk_model2,
                    R.drawable.keranjang_model1,
                    R.drawable.keranjang_model2,
                    R.drawable.keranjang_model3,
                    R.drawable.keranjang_model4,
                    R.drawable.tas_model1),
            intArrayOf(R.drawable.bantal_duduk_model2,
                    R.drawable.tas_model5,
                    R.drawable.tas_model6,
                    R.drawable.tas_model7,
                    R.drawable.tas_model8,
                    R.drawable.tas_model9),
            intArrayOf(R.drawable.keranjang_model1,
                    R.drawable.keranjang_model1,
                    R.drawable.keranjang_model2,
                    R.drawable.keranjang_model3,
                    R.drawable.keranjang_model4,
                    R.drawable.tas_model1),
            intArrayOf(R.drawable.keranjang_model2,
                    R.drawable.tas_model1,
                    R.drawable.tas_model2,
                    R.drawable.tas_model3,
                    R.drawable.tas_model4),
            intArrayOf(R.drawable.keranjang_model3,
                    R.drawable.bantal_duduk_model1,
                    R.drawable.bantal_duduk_model2,
                    R.drawable.keranjang_model1,
                    R.drawable.keranjang_model2,
                    R.drawable.keranjang_model3,
                    R.drawable.keranjang_model4,
                    R.drawable.tas_model1),
            intArrayOf(R.drawable.keranjang_model4,
                    R.drawable.tas_model5,
                    R.drawable.tas_model6,
                    R.drawable.tas_model7,
                    R.drawable.tas_model8,
                    R.drawable.tas_model9),
            intArrayOf(R.drawable.tas_model1,
                    R.drawable.bantal_duduk_model2,
                    R.drawable.keranjang_model1,
                    R.drawable.keranjang_model2,
                    R.drawable.keranjang_model3,
                    R.drawable.keranjang_model4,
                    R.drawable.tas_model1),
            intArrayOf(R.drawable.tas_model2,
                    R.drawable.tas_model5,
                    R.drawable.tas_model6,
                    R.drawable.tas_model7,
                    R.drawable.tas_model8,
                    R.drawable.tas_model9),
            intArrayOf(R.drawable.tas_model3,
                    R.drawable.bantal_duduk_model2,
                    R.drawable.keranjang_model1,
                    R.drawable.keranjang_model2,
                    R.drawable.keranjang_model3,
                    R.drawable.keranjang_model4,
                    R.drawable.tas_model1),
            intArrayOf(R.drawable.tas_model4,
                    R.drawable.tas_model1,
                    R.drawable.tas_model2,
                    R.drawable.tas_model3,
                    R.drawable.tas_model4),
            intArrayOf(R.drawable.tas_model5,
                    R.drawable.bantal_duduk_model1,
                    R.drawable.bantal_duduk_model2,
                    R.drawable.keranjang_model1,
                    R.drawable.keranjang_model2,
                    R.drawable.keranjang_model3,
                    R.drawable.keranjang_model4,
                    R.drawable.tas_model1),
            intArrayOf(R.drawable.tas_model6,
                    R.drawable.tas_model6,
                    R.drawable.tas_model7,
                    R.drawable.tas_model8,
                    R.drawable.tas_model9),
            intArrayOf(R.drawable.tas_model7,
                    R.drawable.bantal_duduk_model1,
                    R.drawable.bantal_duduk_model2,
                    R.drawable.keranjang_model1,
                    R.drawable.keranjang_model2,
                    R.drawable.keranjang_model3,
                    R.drawable.keranjang_model4,
                    R.drawable.tas_model1),
            intArrayOf(R.drawable.tas_model8,
                    R.drawable.tas_model6,
                    R.drawable.tas_model7,
                    R.drawable.tas_model8,
                    R.drawable.tas_model9),
            intArrayOf(R.drawable.tas_model9,
                    R.drawable.bantal_duduk_model2,
                    R.drawable.keranjang_model1,
                    R.drawable.keranjang_model2,
                    R.drawable.keranjang_model3,
                    R.drawable.keranjang_model4,
                    R.drawable.tas_model1)
    )

    private val penjualanItem = intArrayOf(
        34, 65, 53, 54, 67, 54, 23, 65, 53, 54, 67, 54, 23, 90, 34, 65,34, 65, 53, 54, 67, 54, 23, 65, 53, 54, 67, 54, 23, 90, 34, 65
    )

    val listData: ArrayList<DataModelItem>
        get() {
            val list = arrayListOf<DataModelItem>()
            for (position in namaItem.indices){
                val item = DataModelItem()
                item.nama = namaItem[position]
                item.harga = hargaItem[position]
                item.deskripsi = deskripsiItem[position]
//                item.gambar = gambarItem[position]
                item.penjualan = penjualanItem[position]
                item.gambarCarosel = gambarCarousel[position]
                list.add(item)
            }
            return list
        }
}
